LOG_DIR: "./exps/"
FRAME_IDXS: [-2, -1, 0, ]
MAX_DISP: 48

CHECKPOINT:
  EVERY_N_TRAIN_STEPS: 0
  EVERY_N_EPOCHS: 2

TRAINER:
  NAME: "TemporalStereo"
  NUM_GPUS: 1
  GRADIENT_CLIP_VAL: 0.1
  VERSION: "mvsec/pose3/split3/test2"
  MAX_EPOCHS: 16
  CHECK_VAL_EVERY_N_EPOCHS: 1
  LOG_EVERY_N_STEPS: 40
  LOAD_FROM_CHECKPOINT: "exps/TemporalStereo/mvsec/pose3/split3/epoch=011.ckpt"

SCHEDULER:
  TYPE: 'MultiStepLR'
  MULTI_STEP_LR:
    MILESTONES: [12,]
    GAMMA: 0.1

OPTIMIZER:
  TYPE: 'RMSProp'
  RMSPROP:
    LR: 1e-4

MODEL:
  WITH_PREVIOUS: True
  PREVIOUS_WITH_GRADIENT: False
  USE_PAST_COST: True
  LOCAL_MAP_SIZE: 3
  BACKBONE:
    NAME: "TEMPORALSTEREO"
    IN_PLANES: 3
    MEMORY_PERCENT: 0.5
  AGGREGATION:
    NAME: "TEMPORALSTEREO"
    COARSE:
      IN_PLANES: 256
      C: 32
      NUM_SAMPLE: 12
      DELTA: 1.0
      BLOCK_COST_SCALE: 3
      TOPK: 2
      SPATIAL_FUSION: True
    FINE:
      IN_PLANES: 128
      C: 16
      NUM_SAMPLE: 5
      DELTA: 1.0
      BLOCK_COST_SCALE: 3
      TOPK: 2
      SPATIAL_FUSION: True
    PRECISE:
      IN_PLANES: 64
      C: 8
      NUM_SAMPLE: 5
      DELTA: 1.0
      BLOCK_COST_SCALE: 3
      TOPK: 2
  LOSSES:
    SMOOTH_L1_LOSS:
      GLOBAL_WEIGHT: 1.0
      WEIGHTS: [2.0, 1.0, 0.7, 0.5]
      SPARSE: True
      MAX_DISP: 36.42857 #255/7
    WARSSERSTEIN_DISTANCE_LOSS:
      GLOBAL_WEIGHT: 2.0
      WEIGHTS: [1.0, 0.7, 0.5]
      SPARSE: True
      MAX_DISP: 36.42857

DATA:
  TRAIN:
    TYPE: "MVSEC"
    # DATA_ROOT: "/home/user/jaeyoung/data/KITTI-2015/"
    DATA_ROOT: "/home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/"
    ANNFILE: "/home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/view_4_train_v5_split3.json"
    BATCH_SIZE: 2
    NUM_WORKERS: 4
    USE_COMMON_INTRINSICS: False
    DO_SAME_LR_TRANSFORM: False
    HEIGHT: 272
    WIDTH: 352
    # FRAME_IDXS: [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, ]
    FRAME_IDXS: [-2, -1, 0, ]
  VAL:
    TYPE: "MVSEC"
    # DATA_ROOT: "/home/user/jaeyoung/data/KITTI-2015/"
    DATA_ROOT: "/home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset"
    ANNFILE: "/home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/view_4_val_v7_split3_shuffle.json"
    BATCH_SIZE: 4
    NUM_WORKERS: 4
    USE_COMMON_INTRINSICS: False
    DO_SAME_LR_TRANSFORM: True
    HEIGHT: 272
    WIDTH: 352
    # FRAME_IDXS: [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, ]
    FRAME_IDXS: [-2, -1, 0, ]
  TEST:
    TYPE: "MVSEC"
    # DATA_ROOT: "/home/user/jaeyoung/data/KITTI-2015/"
    DATA_ROOT: "/home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/"
    ANNFILE: "/home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/view_4_test_v5_split3_shuffle.json"
    BATCH_SIZE: 8
    NUM_WORKERS: 4
    USE_COMMON_INTRINSICS: False
    DO_SAME_LR_TRANSFORM: True
    HEIGHT: 272
    WIDTH: 352
    # FRAME_IDXS: [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, ]
    FRAME_IDXS: [-2, -1, 0, ]

VAL:
  DO_OCCLUSION_EVALUATION: False
  UPPERBOUND: 36.42857
