wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.12
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698232754.723507
    t:
      1:
      - 1
      - 9
      - 41
      - 43
      - 50
      - 55
      - 63
      2:
      - 1
      - 9
      - 41
      - 43
      - 50
      - 55
      - 63
      3:
      - 7
      - 23
      4: 3.8.10
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
MAX_DISP:
  desc: null
  value: 192
FRAME_IDXS:
  desc: null
  value:
  - -3
  - -2
  - -1
  - 0
LOG_DIR:
  desc: null
  value: ./exps/
DATA/TRAIN/DATA_ROOT:
  desc: null
  value: /home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/
DATA/TRAIN/TYPE:
  desc: null
  value: MVSEC
DATA/TRAIN/ANNFILE:
  desc: null
  value: /home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/view_4_train.json
DATA/TRAIN/HEIGHT:
  desc: null
  value: 256
DATA/TRAIN/WIDTH:
  desc: null
  value: 336
DATA/TRAIN/USE_COMMON_INTRINSICS:
  desc: null
  value: false
DATA/TRAIN/DO_SAME_LR_TRANSFORM:
  desc: null
  value: false
DATA/TRAIN/MEAN:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
DATA/TRAIN/STD:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
DATA/TRAIN/FRAME_IDXS:
  desc: null
  value:
  - -3
  - -2
  - -1
  - 0
DATA/TRAIN/BATCH_SIZE:
  desc: null
  value: 2
DATA/TRAIN/NUM_WORKERS:
  desc: null
  value: 12
DATA/VAL/DATA_ROOT:
  desc: null
  value: /home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset
DATA/VAL/TYPE:
  desc: null
  value: MVSEC
DATA/VAL/ANNFILE:
  desc: null
  value: /home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/view_4_test.json
DATA/VAL/HEIGHT:
  desc: null
  value: 272
DATA/VAL/WIDTH:
  desc: null
  value: 352
DATA/VAL/USE_COMMON_INTRINSICS:
  desc: null
  value: false
DATA/VAL/DO_SAME_LR_TRANSFORM:
  desc: null
  value: true
DATA/VAL/MEAN:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
DATA/VAL/STD:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
DATA/VAL/FRAME_IDXS:
  desc: null
  value:
  - -3
  - -2
  - -1
  - 0
DATA/VAL/BATCH_SIZE:
  desc: null
  value: 1
DATA/VAL/NUM_WORKERS:
  desc: null
  value: 4
DATA/TEST/DATA_ROOT:
  desc: null
  value: /home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/
DATA/TEST/TYPE:
  desc: null
  value: MVSEC
DATA/TEST/ANNFILE:
  desc: null
  value: /home/jaeyoung/data/ws/event_stereo_ICCV2019/dataset/view_4_test.json
DATA/TEST/HEIGHT:
  desc: null
  value: 256
DATA/TEST/WIDTH:
  desc: null
  value: 344
DATA/TEST/USE_COMMON_INTRINSICS:
  desc: null
  value: false
DATA/TEST/DO_SAME_LR_TRANSFORM:
  desc: null
  value: true
DATA/TEST/MEAN:
  desc: null
  value:
  - 0.485
  - 0.456
  - 0.406
DATA/TEST/STD:
  desc: null
  value:
  - 0.229
  - 0.224
  - 0.225
DATA/TEST/FRAME_IDXS:
  desc: null
  value:
  - -3
  - -2
  - -1
  - 0
DATA/TEST/BATCH_SIZE:
  desc: null
  value: 1
DATA/TEST/NUM_WORKERS:
  desc: null
  value: 1
CHECKPOINT/EVERY_N_TRAIN_STEPS:
  desc: null
  value: 0
CHECKPOINT/EVERY_N_EPOCHS:
  desc: null
  value: 4
TRAINER/NAME:
  desc: null
  value: TemporalStereo
TRAINER/VERSION:
  desc: null
  value: mvsec/quad
TRAINER/NUM_GPUS:
  desc: null
  value: 2
TRAINER/NUM_NODES:
  desc: null
  value: 1
TRAINER/MAX_EPOCHS:
  desc: null
  value: 16
TRAINER/MIN_EPOCHS:
  desc: null
  value: 1
TRAINER/MIN_STEPS:
  desc: null
  value: 1000
TRAINER/PRECISION:
  desc: null
  value: 32
TRAINER/AMP_LEVEL:
  desc: null
  value: '00'
TRAINER/SYNC_BATCHNORM:
  desc: null
  value: true
TRAINER/GRADIENT_CLIP_VAL:
  desc: null
  value: 0.1
TRAINER/LOG_EVERY_N_STEPS:
  desc: null
  value: 50
TRAINER/FLUSH_LOGS_EVERY_N_STEPS:
  desc: null
  value: 100
TRAINER/CHECK_VAL_EVERY_N_EPOCHS:
  desc: null
  value: 4
TRAINER/RESUME_FROM_CHECKPOINT:
  desc: null
  value: ''
TRAINER/LOAD_FROM_CHECKPOINT:
  desc: null
  value: ./projects/TemporalStereo/exps/sceneflow.ckpt
TRAINER/FAST_DEV_RUN:
  desc: null
  value: false
OPTIMIZER/TYPE:
  desc: null
  value: RMSProp
OPTIMIZER/RMSPROP/LR:
  desc: null
  value: 0.0001
OPTIMIZER/ADAM/LR:
  desc: null
  value: 0.001
OPTIMIZER/ADAM/BETAS:
  desc: null
  value:
  - 0.9
  - 0.999
OPTIMIZER/ADAMW/LR:
  desc: null
  value: 0.001
OPTIMIZER/ADAMW/BETAS:
  desc: null
  value:
  - 0.9
  - 0.999
OPTIMIZER/ADAMW/WEIGHT_DECAY:
  desc: null
  value: 0.0001
SCHEDULER/TYPE:
  desc: null
  value: MultiStepLR
SCHEDULER/MULTI_STEP_LR/MILESTONES:
  desc: null
  value:
  - 12
SCHEDULER/MULTI_STEP_LR/GAMMA:
  desc: null
  value: 0.1
SCHEDULER/EXPONENTIAL_LR/GAMMA:
  desc: null
  value: 0.9
MODEL/WITH_PREVIOUS:
  desc: null
  value: true
MODEL/PREVIOUS_WITH_GRADIENT:
  desc: null
  value: false
MODEL/WITH_FLOW:
  desc: null
  value: false
MODEL/USE_LOCAL_MAP:
  desc: null
  value: false
MODEL/USE_PAST_COST:
  desc: null
  value: true
MODEL/LOCAL_MAP_SIZE:
  desc: null
  value: 3
MODEL/VIS_FEATURE:
  desc: null
  value: false
MODEL/BACKBONE/NAME:
  desc: null
  value: TEMPORALSTEREO
MODEL/BACKBONE/IN_PLANES:
  desc: null
  value: 3
MODEL/BACKBONE/ALPHA:
  desc: null
  value: 1.0
MODEL/BACKBONE/USE_GRU:
  desc: null
  value: false
MODEL/BACKBONE/MEMORY_PERCENT:
  desc: null
  value: 0.5
MODEL/BACKBONE/NORM:
  desc: null
  value: BN
MODEL/BACKBONE/ACTIVATION:
  desc: null
  value: SiLU
MODEL/AGGREGATION/NAME:
  desc: null
  value: TEMPORALSTEREO
MODEL/AGGREGATION/NORM:
  desc: null
  value: BN
MODEL/AGGREGATION/ACTIVATION:
  desc: null
  value: SiLU
MODEL/AGGREGATION/COARSE/IN_PLANES:
  desc: null
  value: 256
MODEL/AGGREGATION/COARSE/C:
  desc: null
  value: 32
MODEL/AGGREGATION/COARSE/NUM_SAMPLE:
  desc: null
  value: 12
MODEL/AGGREGATION/COARSE/DELTA:
  desc: null
  value: 1.0
MODEL/AGGREGATION/COARSE/BLOCK_COST_SCALE:
  desc: null
  value: 3
MODEL/AGGREGATION/COARSE/SPATIAL_FUSION:
  desc: null
  value: true
MODEL/AGGREGATION/COARSE/TOPK:
  desc: null
  value: 2
MODEL/AGGREGATION/COARSE/NORM:
  desc: null
  value: BN3d
MODEL/AGGREGATION/COARSE/ACTIVATION:
  desc: null
  value: SiLU
MODEL/AGGREGATION/FINE/IN_PLANES:
  desc: null
  value: 128
MODEL/AGGREGATION/FINE/C:
  desc: null
  value: 16
MODEL/AGGREGATION/FINE/NUM_SAMPLE:
  desc: null
  value: 5
MODEL/AGGREGATION/FINE/DELTA:
  desc: null
  value: 1.0
MODEL/AGGREGATION/FINE/BLOCK_COST_SCALE:
  desc: null
  value: 3
MODEL/AGGREGATION/FINE/SPATIAL_FUSION:
  desc: null
  value: true
MODEL/AGGREGATION/FINE/TOPK:
  desc: null
  value: 2
MODEL/AGGREGATION/FINE/NORM:
  desc: null
  value: BN3d
MODEL/AGGREGATION/FINE/ACTIVATION:
  desc: null
  value: SiLU
MODEL/AGGREGATION/PRECISE/IN_PLANES:
  desc: null
  value: 64
MODEL/AGGREGATION/PRECISE/C:
  desc: null
  value: 8
MODEL/AGGREGATION/PRECISE/NUM_SAMPLE:
  desc: null
  value: 5
MODEL/AGGREGATION/PRECISE/DELTA:
  desc: null
  value: 1.0
MODEL/AGGREGATION/PRECISE/BLOCK_COST_SCALE:
  desc: null
  value: 3
MODEL/AGGREGATION/PRECISE/TOPK:
  desc: null
  value: 2
MODEL/AGGREGATION/PRECISE/NORM:
  desc: null
  value: BN3d
MODEL/AGGREGATION/PRECISE/ACTIVATION:
  desc: null
  value: SiLU
MODEL/LOSSES/WARSSERSTEIN_DISTANCE_LOSS/MAX_DISP:
  desc: null
  value: 192
MODEL/LOSSES/WARSSERSTEIN_DISTANCE_LOSS/START_DISP:
  desc: null
  value: 0
MODEL/LOSSES/WARSSERSTEIN_DISTANCE_LOSS/GLOBAL_WEIGHT:
  desc: null
  value: 2.0
MODEL/LOSSES/WARSSERSTEIN_DISTANCE_LOSS/WEIGHTS:
  desc: null
  value:
  - 1.0
  - 0.7
  - 0.5
MODEL/LOSSES/WARSSERSTEIN_DISTANCE_LOSS/SPARSE:
  desc: null
  value: true
MODEL/LOSSES/SMOOTH_L1_LOSS/MAX_DISP:
  desc: null
  value: 192
MODEL/LOSSES/SMOOTH_L1_LOSS/START_DISP:
  desc: null
  value: 0
MODEL/LOSSES/SMOOTH_L1_LOSS/GLOBAL_WEIGHT:
  desc: null
  value: 1.0
MODEL/LOSSES/SMOOTH_L1_LOSS/WEIGHTS:
  desc: null
  value:
  - 2.0
  - 1.0
  - 0.7
  - 0.5
MODEL/LOSSES/SMOOTH_L1_LOSS/SPARSE:
  desc: null
  value: true
VAL/VIS_INTERVAL:
  desc: null
  value: 3
VAL/VIS_BATCH_INDEX:
  desc: null
  value: 4
VAL/LOWERBOUND:
  desc: null
  value: 0
VAL/UPPERBOUND:
  desc: null
  value: 192
VAL/DO_OCCLUSION_EVALUATION:
  desc: null
  value: false
VAL/EVAL_DISPARITY_IDS:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
